### ISSUE TITLE
Error when update to Scala 2.12

### ISSUE THREAD

**Issue by mingchuno** [jhole89/aws-glue-sbt-quickstart#1]
Try to update with `scalaVersion in ThisBuild := "2.12.11"` but fail with the following error:

```
[error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/aws-glue-sbt-quickstart/"), "shared"):
[error]    org.scala-lang.modules:scala-xml _2.12, _2.11
[error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/aws-glue-sbt-quickstart/"), "root"):
[error]    org.scala-lang.modules:scala-xml _2.12, _2.11
```

**Comment by jhole89** [comment]
Thanks @mingchuno I'll try and have a look over the weekend. A very quick look seems to trace the issue to scalatest (but I could be wrong).

**Comment by mingchuno** [comment]
@jhole89 I found that the `update` task failed after I have updated the scala version. And I have tried to comment out the `scalatest` depns and the update task work! But I am not sure about the reason behind.

**Comment by rgarcia** [comment]
FYI according to https://docs.aws.amazon.com/glue/latest/dg/console-custom-created.html "Currently, only pure Java or Scala (2.11) libraries can be used."

**Comment by mingchuno** [comment]
Okay, maybe I will close this issue.

**Comment by jhole89** [comment]
Thanks @rgarcia I'll create an issue to track Scala 2.12 as I believe it should get supported at some point in the far future (unfortunately not with Glue 2.0.0 AFAIK).

I spent some time over the weekend and I think there may be a way to hack it by excluding scala-xml from the AWS lib, but there's no guarantee that would compile at the Glue run stage.

**Comment by mingchuno** [comment]
@jhole89 Ya...Even if we can hack it by excluding depns from AWS lib, we are not sure the Glue job can be run with 2.12 compiled jars until offical support from AWS.
